defmodule HermesBeam.Changes.CompileSkillModule do
  @moduledoc """
  Ash Change that compiles LLM-generated Elixir source code into a live BEAM
  module and registers the module name on the changeset.

  If compilation fails, `{:error, reason}` is returned so the calling Reactor
  step can invoke its `undo/3` compensation to prompt the LLM to rewrite.

  Security note: dynamically compiled code runs with the same privileges as
  the BEAM node. Future iterations should evaluate sandboxing via WASM
  (see ROADMAP.md — Future Considerations).
  """
  use Ash.Resource.Change
  require Logger

  @impl true
  def change(changeset, _opts, _ctx) do
    elixir_code = Ash.Changeset.get_attribute(changeset, :elixir_code)
    skill_name  = Ash.Changeset.get_attribute(changeset, :name)

    case compile_skill(skill_name, elixir_code) do
      {:ok, module_name} ->
        Logger.info("[CompileSkillModule] Compiled skill '#{skill_name}' as #{module_name}")
        Ash.Changeset.change_attribute(changeset, :module_name, Atom.to_string(module_name))

      {:error, reason} ->
        Logger.warning("[CompileSkillModule] Compilation failed for '#{skill_name}': #{inspect(reason)}")
        Ash.Changeset.add_error(changeset, field: :elixir_code, message: "Compilation failed: #{inspect(reason)}")
    end
  end

  # ---------------------------------------------------------------------------
  # Private
  # ---------------------------------------------------------------------------

  defp compile_skill(skill_name, elixir_code) do
    # Wrap the code in a uniquely namespaced module to avoid conflicts.
    sanitized_name =
      skill_name
      |> String.replace(~r/[^a-zA-Z0-9_]/, "_")
      |> String.capitalize()

    module_name = String.to_atom("HermesBeam.Skills.Dynamic.#{sanitized_name}")

    # Purge any existing version of this module before recompiling.
    if :code.is_loaded(module_name) do
      :code.purge(module_name)
      :code.delete(module_name)
    end

    wrapped_code = """
    defmodule #{module_name} do
      @moduledoc \"\"\"
      Dynamically compiled skill: #{skill_name}.
      Generated by Hermes BEAM agent.
      \"\"\"

      #{elixir_code}
    end
    """

    try do
      [{^module_name, _bytecode}] = Code.compile_string(wrapped_code)
      {:ok, module_name}
    rescue
      e in [CompileError, SyntaxError, TokenMissingError] ->
        {:error, Exception.message(e)}
    catch
      :error, reason ->
        {:error, reason}
    end
  end
end
